server:
  port: ${PORT}
spring:
  cloud:
    gateway:
      default-filters:
        - StripPrefix=1
      routes:
        - id: catalog-service
          uri: http://catalog-service:8001
          predicates:
            - Path=/api/catalog/**