version: '3.7'

services:
  users-db:
    image: postgres:11
    ports:
      - 9000:5432
    environment:
      - POSTGRES_DB=usersdb
      - POSTGRES_USER=usersdb
      - POSTGRES_PASSWORD=usersdb
    volumes:
      - ./.data/usersdb:/var/lib/postgresql/data  
