version: '3.7'

services:
  usersdb:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=usersdb
      - POSTGRES_USER=usersdb
      - POSTGRES_PASSWORD=usersdb
    volumes:
      - ./.data/usersdb:/var/lib/postgresql/data  
  catalogdb:
    image: mysql:5.7
    volumes:
      - .data/catalogdb:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: catalogdb
        MYSQL_DATABASE: catalogdb
        MYSQL_USER: catalogdb
        MYSQL_PASSWORD: catalogdb
  basketdb:
    image: mongo:6.0
    volumes:
      - .data/basketdb:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: basketdb
      MONGO_INITDB_ROOT_PASSWORD: basketdb