apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 8080
  selector:
    app: catalog-service
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
      - image: ghcr.io/juandaabril/microservices-demo-catalog-service:0.0.15
        name: catalog-service
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: DATABASE_HOST
            value: catalogdb
          - name: DATABASE_PORT
            value: "3306"
          - name: DATABASE_NAME
            value: catalogdb
          - name: DATABASE_USERNAME
            value: catalogdb
          - name: DATABASE_PASSWORD
            value: catalogdb
