apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog-service
  ports:
  - port: 8001
    targetPort: 8001
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
      - image: ghcr.io/juandaabril/microservices-demo/catalog-service:0.0.17
        name: catalog-service
        ports:
        - containerPort: 8001
        env:
          - name: PORT
            value: "8001"
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: configurations
                key: CATALOG_DATABASE_HOST
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: configurations
                key: CATALOG_DATABASE_PORT
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: secrets
                key: CATALOG_DATABASE_NAME
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: secrets
                key: CATALOG_DATABASE_USERNAME
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets
                key: CATALOG_DATABASE_PASSWORD
