apiVersion: v1
kind: PersistentVolume
metadata:
  name: catalogdb-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/catalogdb
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalogdb-pvc
spec:
  volumeName: catalogdb-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi 
---
apiVersion: v1
kind: Service
metadata:
  name: catalogdb
spec:
  ports:
  - port: 5433
    protocol: TCP
    targetPort: 5432
  selector:
    app: catalogdb
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogdb
  template:
    metadata:
      labels:
        app: catalogdb
    spec:
      containers:
      - image: postgres:11
        name: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: secrets
                key: CATALOG_DATABASE_NAME
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: secrets
                key: CATALOG_DATABASE_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets
                key: CATALOG_DATABASE_PASSWORD
        volumeMounts:
          - name: data-catalogdb
            mountPath: /var/lib/postgresql/data  
      volumes:
        - name: data-catalogdb
          persistentVolumeClaim:
            claimName: catalogdb-pvc