apiVersion: v1
kind: Service
metadata:
  name: catalogdb
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: catalogdb
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogdb
  template:
    metadata:
      labels:
        app: catalogdb
    spec:
      containers:
      - image: mariadb:10.9.2
        name: mariadb
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: catalogdb
          - name: MYSQL_DATABASE
            value: catalogdb
          - name: MYSQL_USER
            value: catalogdb
          - name: MYSQL_PASSWORD
            value: catalogdb