apiVersion: v1
kind: Service
metadata:
  name: catalog-service-svc
spec:
  selector:
    app: catalog-service
  ports:
  - port: 8001
    targetPort: 8001
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
      - image: ghcr.io/juandaabril/microservices-demo/catalog-service:0.0.16
        name: catalog-service
        ports:
        - containerPort: 8001
        env:
          - name: PORT
            value: 8001
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: catalog-config
                key: database_name
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: catalog-config
                key: database_port
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: catalog-config
                key: database_name
          - name: DATABASE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: catalog-config
                key: database_username
          - name: DATABASE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: catalog-config
                key: database_password
