apiVersion: v1
kind: ConfigMap
metadata:
  name: configurations
data:
  CATALOG_DATABASE_HOST: catalogdb
  CATALOG_DATABASE_PORT: "5433"
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  CATALOG_DATABASE_NAME: Y2F0YWxvZ2Ri
  CATALOG_DATABASE_USERNAME: Y2F0YWxvZ191c3I=
  CATALOG_DATABASE_PASSWORD: Y2F0YWxvZ19wYXNz