version: '3.7'

services:
  catalogdb:
    image: mysql:5.7
    volumes:
      - .data/catalogdb:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: catalogdb
        MYSQL_DATABASE: catalogdb
        MYSQL_USER: catalogdb
        MYSQL_PASSWORD: catalogdb
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
  user-service:
    image: ghcr.io/juandaabril/microservices-demo-catalog-service:0.0.14
    ports:
      - "8080:8080"
    environment:
        PORT: 8080
        DATABASE_HOST: catalogdb
        DATABASE_PORT: 3306
        DATABASE_NAME: catalogdb
        DATABASE_USERNAME: catalogdb
        DATABASE_PASSWORD: catalogdb
    depends_on:
      catalogdb:
        condition: service_healthy