### GET ALL baskets
GET http://localhost:8080/api/basket
Accept: application/json

### GET BASKET BY USER_ID
GET http://localhost:8080/api/basket/get-basket-by-userid/1
Accept: application/json

### ADD PRODUCT TO THE BASKET
PUT http://localhost:8080/api/basket
Content-Type: application/json

{
  "userId":  1,
  "product": {
    "id": 2,
    "name": "any product2kk",
    "unitPrice": 200,
    "oldUnitPrice": 100,
    "quantity": 2,
    "pictureUrl": "some-url"
  }
}
