name: Catalog Service

on:
  push:
    tags:
      - 'catalog-service/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build
        run: cd ./catalog-service && ./gradlew build
      - name: Test
        run: cd ./catalog-service && ./gradlew test
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Version
        run: echo "IMAGE_VERSION=$(git describe --exact-match --tags 2> /dev/null || echo 'latest')" >> $GITHUB_ENV
      - name: Split Version
        uses: rishabhgupta/split-by@v1
        id: split
        with:
          string: '${{ env.IMAGE_VERSION }}'
          split-by: '/'
      - name: Test
        run: echo ${{ steps.split.outputs._0 }}
      - name: Test
        run: echo ${{ steps.split.outputs._1 }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./catalog-service
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ steps.split.outputs._0 }}:${{ steps.split.outputs._1 }}