name: Catalog Service Workflow

on:
  push:
    branches: [master]
    paths:
      - catalog-service/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build
        run: cd ./catalog-service && ./gradlew build
      - name: Test
        run: cd ./catalog-service && ./gradlew test